version: '3.8'

services:
 urlshortener_app:
  build:
   context: .
   dockerfile: Dockerfile
   args:
    SPRING_TEST_PORT: ${SPRING_TEST_PORT}
    APP_CONTEXT_PATH: ${APP_CONTEXT_PATH}
    LOCAL_HOST: ${LOCAL_HOST}
    KEY_ALPHABETS: ${KEY_ALPHABETS}
    KEY_LENGTH: ${KEY_LENGTH}
  restart: always
  ports:
   - ${SPRING_PORT}:${SPRING_PORT}
  environment:
   - SPRING_TEST_PORT=${SPRING_TEST_PORT}
   - APP_CONTEXT_PATH=${APP_CONTEXT_PATH}
   - LOCAL_HOST=${LOCAL_HOST}
   - SPRING_PORT=${SPRING_PORT}
   - KEY_ALPHABETS=${KEY_ALPHABETS}
   - KEY_LENGTH=${KEY_LENGTH}
   - LOCAL_POSTGRES_BASE_URL=${DOCKER_POSTGRES_BASE_URL}
   - URL_SHORTENER_DB=${URL_SHORTENER_DB}
   - DEV_POSTGRES_USER=${DEV_POSTGRES_USER}
   - DEV_POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
   - DEV_POSTGRES_PORT=${DEV_POSTGRES_PORT}
  depends_on:
   - db
 db:
  image: postgres
  restart: always
  ports:
   - ${DEV_POSTGRES_PORT}:${DEV_POSTGRES_PORT}
  environment:
   POSTGRES_DB: ${URL_SHORTENER_DB}
   POSTGRES_USER: ${DEV_POSTGRES_USER}
   POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}